### ISSUE TITLE
Navbar Disappears Unexpectedly When Scrolling

### ISSUE THREAD

**Issue by NewtonFernandis** [NewtonFernandis/IssueHunter#1]
**Description:**

**Issue Overview:**
When scrolling through the webpage, the navbar unexpectedly disappears. This issue needs to be addressed to ensure a smooth user experience.

**Steps to Reproduce:**
1. Simply scroll down the page.
2. Observe that the navbar disappears when scrolling, which is not the intended behavior.

**Expected Behavior:**
The navbar should remain visible and functional while scrolling.

**Actual Behavior:**
The navbar disappears abruptly when scrolling.

**Comment by Baburao-sanivada** [comment]
Can I Work On this Issue?

**Comment by NewtonFernandis** [comment]
Absolutely, you're welcome to work on this issue! Your help is greatly appreciated.

**Comment by NewtonFernandis** [comment]
@Baburao-sanivada Hi, Any update on this?

**Comment by Baburao-sanivada** [comment]
Will Solve it by Tommorow?
Is That Fine?

**Comment by NewtonFernandis** [comment]
> Will Solve it by Tommorow? Is That Fine?

Yeap, totally fine take your time. Just wanted to check.

**Comment by NewtonFernandis** [comment]
@Baburao-sanivada Sorry, Closing this issue as this has been solved in another PR. Thank you
