### ISSUE TITLE
feat: Implement Redirect Home Functionality on Logo Click

### ISSUE THREAD

**Issue by purnasth** [NewtonFernandis/IssueHunter#17]
# Issue Title: Implement Redirect Functionality on Logo Click

## Issue Description
The logo from the header section is non-functional. Presently, clicking on the logo does not redirect users. This enhancement proposes implementing functionality such that when users click on the logo in the header section, it redirects them to the home page.

## Proposed Changes
- Implement redirection functionality for the "Issue Hunter" logo in the header section to direct users to the home page.

## Attachments
![image](https://github.com/NewtonFernandis/IssueHunter/assets/107195487/2e5a022d-f7ec-4050-8fa4-57d530a82db3)

## Additional Information
Adding the functionality to the logo will enhance user navigation by providing a direct way to return to the home page. This change aligns with standard website behavior, offering users an intuitive method to navigate back to the main page.

**Comment by KriteshTimsina** [comment]
From which page do you exactly want to redirect to homepage? There's only one single page and that's the Homepage.

**Comment by purnasth** [comment]
> From which page do you exactly want to redirect to homepage? There's only one single page and that's the Homepage.

What if the user clicks the next button and goes to the tenth page? How can he return to the home page? by refreshing the website?

**Comment by KriteshTimsina** [comment]
Well, that makes sense.
