### ISSUE TITLE
Fix button overflow issue

### ISSUE THREAD

**Issue by NewtonFernandis** [NewtonFernandis/IssueHunter#2]
<img width="765" alt="Screenshot 2023-10-03 at 11 08 24 PM" src="https://github.com/NewtonFernandis/IssueHunter/assets/121332168/a94409d2-e2c1-4085-ae8b-0963a5784bc9">

## Issue
As you can see in the screenshot, the buttons are overflowing from the card. To fix this I guess it's better to add a horizontal scroller for tags.

**Comment by raji2004** [comment]
please assign me this issue

**Comment by AniswagMC** [comment]
I'd love to solve this for you! 🤗

**Comment by NewtonFernandis** [comment]
> please assign me this issue

Absolutely, you're welcome to work on this issue! Your help is greatly appreciated.

**Comment by NewtonFernandis** [comment]
@raji2004 Are you working on this?

**Comment by NewtonFernandis** [comment]
@tmatheas Assigning this to you
