### ISSUE TITLE
Implement Scroll-to-Top Functionality on Pagination Next Button Click

### ISSUE THREAD

**Issue by NewtonFernandis** [NewtonFernandis/IssueHunter#4]
**Issue Description:**
Currently, when users navigate through paginated content and click the "Next" button, there is no automatic scroll to the top of the page. This can lead to a less-than-optimal user experience, especially on pages with long content. To enhance user navigation and readability, we should implement a scroll-to-top feature that triggers when the "Next" button is clicked.

**Expected Behavior:**
- When a user clicks the "Next" button on the pagination control, the page should smoothly scroll to the top of the content.

**Actual Behavior:**
- Currently, when the "Next" button is clicked, there is no automatic scrolling to the top of the page. Users are required to manually scroll back to the top if they wish to start reading from the beginning of the newly loaded content.

**Comment by thesloppyguy** [comment]
@NewtonFernandis created a PR to resolve this issue and it also resolves #1 , please review when possible.

**Comment by NewtonFernandis** [comment]
Thanks for your contribution ❤️
